### ISSUE TITLE
dummy cli command seems broken

### ISSUE THREAD

**Issue by slamora** [eReuse/devicehub-teal#192]
When I try to run `dummy` on a clean environment I get the following error:
```
psycopg2.errors.UndefinedFunction: function websearch_to_tsquery
```

## Steps to reproduce the issue:
1. Initialize database
```
bash examples/create-db.sh
```
2.  Run dummy cli command:
```
export dhi=dbtest;  dh dummy
```

### Traceback
```python
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "env/bin/dh", line 11, in <module>
    load_entry_point('ereuse-devicehub', 'console_scripts', 'dh')()
  File "devicehub-teal/env/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "devicehub-teal/ereuse_devicehub/cli.py", line 42, in main
    return super().main(*args, **kwargs)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "devicehub-teal/env/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "devicehub-teal/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "devicehub-teal/env/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "devicehub-teal/env/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "devicehub-teal/env/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "devicehub-teal/env/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "devicehub-teal/ereuse_devicehub/dummy/dummy.py", line 163, in run
    i, _ = user1.get(res=Device, query=[('search', 'intel')])
  File "devicehub-teal/ereuse_devicehub/client.py", line 48, in get
    return super().get(uri, res, query, status, item, accept, headers, token, **kw)
  File "devicehub-teal/env/lib/python3.8/site-packages/teal/client.py", line 75, in get
    return super().get(uri, query, item, status, accept, headers, **kw)
  File "devicehub-teal/env/lib/python3.8/site-packages/ereuse_utils/test.py", line 105, in get
    return super().get(uri, item=item, status=status, accept=accept, headers=headers,
  File "devicehub-teal/env/lib/python3.8/site-packages/werkzeug/test.py", line 830, in get
    return self.open(*args, **kw)
  File "devicehub-teal/ereuse_devicehub/client.py", line 151, in open
    return super().open(uri, res, status, query, accept, content_type, item, headers,
  File "devicehub-teal/ereuse_devicehub/client.py", line 35, in open
    return super().open(uri, res, status, query, accept, content_type, item, headers, token,
  File "devicehub-teal/env/lib/python3.8/site-packages/teal/client.py", line 32, in open
    res = super().open(uri, status, query, accept, content_type, item, headers, **kw)
  File "devicehub-teal/env/lib/python3.8/site-packages/ereuse_utils/test.py", line 72, in open
    response = super().open(uri, headers=headers, **kw)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/testing.py", line 196, in open
    return Client.open(
  File "devicehub-teal/env/lib/python3.8/site-packages/werkzeug/test.py", line 803, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "devicehub-teal/env/lib/python3.8/site-packages/werkzeug/test.py", line 716, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "devicehub-teal/env/lib/python3.8/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "devicehub-teal/env/lib/python3.8/site-packages/teal/resource.py", line 189, in dispatch_request
    return super().dispatch_request(*args, **kwargs)
  File "devicehub-teal/env/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "devicehub-teal/ereuse_devicehub/resources/device/views.py", line 104, in get
    return super().get(id)
  File "devicehub-teal/env/lib/python3.8/site-packages/teal/resource.py", line 210, in get
    response = self.find(args)
  File "devicehub-teal/env/lib/python3.8/site-packages/teal/auth.py", line 44, in decorated
    return f(*args, **kwargs)
  File "devicehub-teal/ereuse_devicehub/resources/device/views.py", line 148, in find
    devices = query.paginate(page=args['page'], per_page=30)  # type: Pagination
  File "devicehub-teal/env/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 491, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2925, in all
    return list(self)
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3081, in __iter__
    return self._execute_and_instances(context)
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3106, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1093, in _execute_clauseelement
    ret = self._execute_context(
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1239, in _execute_context
    self._handle_dbapi_exception(
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1235, in _execute_context
    self.dialect.do_execute(
  File "devicehub-teal/env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function websearch_to_tsquery(unknown, unknown) does not exist
LINE 1: ... device_active, ts_rank(device_search.properties, websearch_...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
 [SQL: 'SELECT DISTINCT device.updated AS device_updated, device.created AS device_created, device.id AS device_id, device.type AS device_type, device.hid AS device_hid, device.model AS device_model, device.manufacturer AS device_manufacturer, device.serial_number AS device_serial_number, device.brand AS device_brand, device.generation AS device_generation, device.version AS device_version, device.weight AS device_weight, device.width AS device_width, device.height AS device_height, device.depth AS device_depth, device.color AS device_color, device.production_date AS device_production_date, device.variant AS device_variant, device.sku AS device_sku, device.image AS device_image, device.owner_id AS device_owner_id, device.allocated AS device_allocated, device.devicehub_id AS device_devicehub_id, device.active AS device_active, ts_rank(device_search.properties, websearch_to_tsquery(%(websearch_to_tsquery_1)s, %(websearch_to_tsquery_2)s)) + ts_rank(device_search.tags, websearch_to_tsquery(%(websearch_to_tsquery_3)s, %(websearch_to_tsquery_4)s)) + ts_rank(device_search.devicehub_ids, websearch_to_tsquery(%(websearch_to_tsquery_5)s, %(websearch_to_tsquery_6)s)) AS anon_1 \nFROM device JOIN device_search ON device.id = device_search.device_id \nWHERE device.active = true AND (device.owner_id = %(owner_id_1)s OR 1 != 1) AND ((device_search.properties @@ websearch_to_tsquery(%(websearch_to_tsquery_7)s, %(websearch_to_tsquery_8)s)) OR (device_search.tags @@ websearch_to_tsquery(%(websearch_to_tsquery_9)s, %(websearch_to_tsquery_10)s)) OR (device_search.devicehub_ids @@ websearch_to_tsquery(%(websearch_to_tsquery_11)s, %(websearch_to_tsquery_12)s))) ORDER BY ts_rank(device_search.properties, websearch_to_tsquery(%(websearch_to_tsquery_1)s, %(websearch_to_tsquery_2)s)) + ts_rank(device_search.tags, websearch_to_tsquery(%(websearch_to_tsquery_3)s, %(websearch_to_tsquery_4)s)) + ts_rank(device_search.devicehub_ids, websearch_to_tsquery(%(websearch_to_tsquery_5)s, %(websearch_to_tsquery_6)s)), device.id ASC \n LIMIT %(param_1)s OFFSET %(param_2)s'] [parameters: {'websearch_to_tsquery_1': 'english', 'websearch_to_tsquery_2': 'intel', 'websearch_to_tsquery_3': 'english', 'websearch_to_tsquery_4': 'intel', 'websearch_to_tsquery_5': 'english', 'websearch_to_tsquery_6': 'intel', 'owner_id_1': UUID('624e65b2-e99b-4a41-8cc2-b46511becf25'), 'websearch_to_tsquery_7': 'english', 'websearch_to_tsquery_8': 'intel', 'websearch_to_tsquery_9': 'english', 'websearch_to_tsquery_10': 'intel', 'websearch_to_tsquery_11': 'english', 'websearch_to_tsquery_12': 'intel', 'param_1': 30, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)

```

**Comment by slamora** [comment]
I've realized that the problem is the Postgres version, `websearch_to_tsquery` has been introduced on [version 11](https://pgpedia.info/w/websearch_to_tsquery.html) and I was working with a Postgres 10!

Sorry for that, my fault.
